version: "3"

services:
  clash:
    image: dreamacro/clash:v1.14.0
    container_name: clash-server
    volumes:
      - ./config.yaml:/root/.config/clash/config.yaml
    ports:
      - "7890:7890"
      - "7891:7891"
      - "9090:9090"
    restart: always
    
  yacd:
    image: haishanh/yacd:v0.3.8
    container_name: clash-dashboard
    ports:
      - "1234:80"
    restart: always
